services:
  prometheus:
    image: quay.io/prometheus/prometheus
    container_name: prometheus
    depends_on:
      - blackbox_exporter
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090
    restart: unless-stopped
    read_only: true
    volumes:
      - ./prometheus:/etc/prometheus:ro
      - prom_data:/prometheus:rw
  blackbox_exporter:
    image: quay.io/prometheus/blackbox-exporter
    container_name: blackbox_exporter
    command:
      - '--config.file=/etc/blackbox_exporter/blackbox.yaml'
    ports:
      - 9115:9115
    restart: unless-stopped
    read_only: true
    volumes:
      - ./blackbox_exporter:/etc/blackbox_exporter:ro
volumes:
  prom_data:
