services:
  prometheus:
    image: quay.io/prometheus/prometheus@sha256:378f4e03703557d1c6419e6caccf922f96e6d88a530f7431d66a4c4f4b1000fe
    container_name: prometheus
    depends_on:
      - blackbox_exporter
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090
    restart: unless-stopped
    read_only: true
    volumes:
      - ./prometheus:/etc/prometheus:ro
      - prom_data:/prometheus:rw
  blackbox_exporter:
    image: quay.io/prometheus/blackbox-exporter@sha256:b04a9fef4fa086a02fc7fcd8dcdbc4b7b35cc30cdee860fdc6a19dd8b208d63e
    container_name: blackbox_exporter
    command:
      - '--config.file=/etc/blackbox_exporter/blackbox.yaml'
    ports:
      - 9115:9115
    restart: unless-stopped
    read_only: true
    volumes:
      - ./blackbox_exporter:/etc/blackbox_exporter:ro
volumes:
  prom_data:
